[project]
name = "pine64-temp-sensor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.3",
    "smbus2>=0.5.0",
    "sqlalchemy>=2.0.41",
]
